<?php echo '<?php'; ?>

/**
 * AUTOMATICALLY GENERATED - DO NOT EDIT.
 *
 * This file was automatically generated by Pharser\Parser\ClassBuilder.
 *
 * Created: <?php echo (new \DateTime())->format('Y-m-d H:i:s'); ?>.
 */

class <?php echo $className; ?> <?php if ($classExtend): ?>extends <?php echo $classExtend; ?><?php endif ?>

{

<?php foreach ($constants as $name => $value) : ?>
const <?php echo $name; ?> = <?php echo $value; ?>;
<?php endforeach; ?>

<?php echo $functions; ?>

}
